### ISSUE TITLE
Add new keyword to set timeout for URL connection

### ISSUE THREAD

**Issue by poliarush** [ombre42/robotframework-sudslibrary#12] opened 2013-10-11 08:17 UTC
It is supported thru _options=timeout_ https://fedorahosted.org/suds/wiki/Documentation

> The URL connection timeout (seconds) default=90.

**Comment by ombre42** [comment] 2013-10-11 14:38
There is already a keyword for this: [Set Soap Timeout](http://ombre42.github.io/robotframework-sudslibrary/doc/SudsLibrary.html#Set%20Soap%20Timeout) and was implemented in the version 0.8. Perhaps you need to upgrade. The timeout can also be set to an initial value in [Create Soap Client](http://ombre42.github.io/robotframework-sudslibrary/doc/SudsLibrary.html#Create%20Soap%20Client) as of 0.8.

Closing as duplicate of issue #5

**Closed as completed by ombre42** 2013-10-11 14:38 UTC
